BaSD-MS 36: Create Profiles View
BaSD-2021/Nico-MindSet-app pull request #1
Opened 2021-11-29 04:00 UTC by ravegliamartin

# Add Profile View

## Components Created:

- ListItem
- Input
- Form
- DeleteBtn
- Modal

## Methods Tested

- List Profiles (Main view)
- Create Profile (By clicking on Add Button at end of list)
- Update Profile (By clicking in the profile row to be edited)
- Delete Profile (On row hover, a delete button appears at the end of the profile row)

2021-12-01 14:59 UTC, nicolasviola requested changes

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/Form/index.js
> +import { useState, useEffect } from 'react';
Deberíamos dejar un salto de linea entre los imports y la función para favorecer al entendimiento del componente mas fácilmente

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/Form/index.js
> +          console.log(error);
Por favor, elimina este console.log

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/Form/index.js
> +          setError('error en use');
Buen trabajo con esta idea de mostrar el error. Te pido que lo muestres en ingles.

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/Form/index.js
> +      ></Input>
Si el elemento no tiene contenido, podrias cerrarlo en la misma etiqueta de apertura:
`<Input></Input>` Sin contenido es lo mismo que hacer `<Input />`

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/ListItem/index.js
> +  // console.log(headerItems);
Please delete this comment

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/index.js
> +  const [modalBtnOnClick, setModalBtnOnClick] = useState([]);
Mmm... Esto no es necesario que sea un useState porque es la función que se va a ejecutar al momento de eliminar un elemento. Por lo general el useState lo usamos para guardar valores de variables, no para guardar metodos. En este caso podrias hacer una funcion que se llame modalButtonOnClick dentro de tu componente, definir los parametros que va a recibir y dentro de esa funcion ejecturar el setShowModal(false) y el fetch que haces despues. Seria:
```
const modalBtnOnClick = () => {
  setShowModal(false)
  fetch...
}
```

2021-12-01 14:59 UTC, nicolasviola commented on src/Components/Profiles/index.js
> +      ></Modal>
Lo mismo aca, podemos cerrar los componentes sin contenido haciendo:
```
<Modal
        showHook={setShowModal}
        showModal={showModal}
        title="You are about to delete a profile"
        subtitle={modalSubtitle}
        btnText={['Close', 'Proceed']}
        btnOnClick={modalBtnOnClick}
        error={modalError}
 />
```

2021-12-02 20:13 UTC, ravegliamartin commented on src/Components/Profiles/Form/index.js
> +          setError('error en use');
Actually i was using that line for debugging, 'cause the returned error message was an empty object. I believe the problem was that I was destructuring the object as `{ message }` but in the server the error sent had a msg attr. Fixed that.

2021-12-02 20:26 UTC, ravegliamartin commented on src/Components/Profiles/index.js
> +  const [modalBtnOnClick, setModalBtnOnClick] = useState([]);
O sea que es recomendable definir las funciones dentro del componente Modal, en lugar de pasarlas desde afuera? Lo había armado asi porque se me hacia mas reutilizable el componente al no tener fijados los métodos de los onClick.

Ahora modifico la lógica, tengo que ver como le paso el Id al modal para poder hacer el fetch.

2021-12-02 20:50 UTC, nicolasviola approved these changes

2021-12-02 20:50 UTC, merged