BaSD-MS-42: Create Input Shared
BaSD-2021/Nico-MindSet-app pull request #11
Opened 2021-12-04 21:48 UTC by Brunomoyano4

### Create Input Shared

- Create input shared and replace it in all components

2021-12-06 18:26 UTC, ravegliamartin requested changes

2021-12-06 18:26 UTC, ravegliamartin commented on src/Components/Shared/Input/input.module.css
> +.container {
This class is not in use. 

Maybe, to help on having a cleaner code is better to remove it. 
Wrapping the `Input` inner elements (`label` and `input`) with a container might be a good idea as well, so it renders as one block parent element with two childs.

2021-12-06 18:26 UTC, ravegliamartin commented on src/Components/Shared/Input/index.js
> +    {!!props.label} {<label className={styles.label}>{props.label}</label>}
I think this line of code should be `{props.label && <label className={styles.label}>{props.label}</label>}` 

Right now it is rendering the `label` tag every time, but it's not visible cause when there is no `props.label` the width is equal to 0.

2021-12-06 18:26 UTC, ravegliamartin commented on src/Components/Shared/Select/index.js
> +      {!!props.label} {<label className={styles.label}>{props.label}</label>}
I think this line of code should be `{props.label && <label className={styles.label}>{props.label}</label>}` 

Right now it is rendering the `label` tag every time, but it's not visible cause when there is no `props.label` the width is equal to 0.

2021-12-06 21:40 UTC, Brunomoyano4 commented on src/Components/Shared/Input/input.module.css
> +.container {
wrapping the inputs is a good idea, but within each form already belong to another container, then we would have as a result a container within another container

2021-12-06 23:46 UTC, nicolasviola requested changes

2021-12-06 23:46 UTC, nicolasviola commented on src/Components/Postulants/Form/postulantsForm.module.css
> +<<<<<<< HEAD:src/Components/Postulants/Form/postulantsForm.module.css
Aca tenes conflictos que no fueron resueltos y comiteaste los cambios sin resolverlos. Por favor chequealo porque va a romper toda la app. Es muy importante probar todo antes de subir los cambios

2021-12-06 23:46 UTC, nicolasviola commented on src/Components/Shared/Input/input.module.css
> +	box-sizing: border-box;
Corregir la indentacion por favor

2021-12-07 02:05 UTC, Brunomoyano4 commented on src/Components/Shared/Input/input.module.css
> +	box-sizing: border-box;
![image](https://user-images.githubusercontent.com/57734335/144941176-d180c1d7-d842-4660-9bd9-ba216d82c534.png)

Se ve que era un problema invisible porque no se me muestra en el código, espero con el formatter se solucione

2021-12-07 02:28 UTC, nicolasviola approved these changes

2021-12-07 02:28 UTC, merged