BaSD-MS-55: Reduce Admins
BaSD-2021/Nico-MindSet-app pull request #20
Opened 2021-12-11 18:07 UTC by Brunomoyano4

### Implement model Admin in redux

**Define call async with states:**
- Fetching
- Fulfilled
- Rejected

Replace old logic in components to replace with redux

2021-12-13 04:01 UTC, ravegliamartin requested changes

2021-12-13 04:01 UTC, ravegliamartin commented on src/redux/admins/thunks.js
> +        return response.data;
the response.data returned is not in use, it might be removed.

2021-12-13 20:44 UTC, nicolasviola requested changes

2021-12-13 20:44 UTC, nicolasviola commented on src/Components/Admins/Form/index.js
> +    dispatch(getAdmins());
No hace falta hacer otro dispatch para traer la lista nuevamente desde esta vista, porque al redireccionar a la ruta anterior se deberia hacer un getAdmins nuevamente desde el useEffect de ese componente

2021-12-13 20:44 UTC, nicolasviola commented on src/redux/admins/reducer.js
> +        isLoading: false
No estas agregando el nuevo admin. Insisto que revises la implementacion que hizo Esteban que está exactamente este ejemplo

2021-12-13 20:44 UTC, nicolasviola commented on src/redux/admins/reducer.js
> +        list: state.list.filter((admins) => admins._id !== action.payload)
No tiene sentido este updated, con la redirección deberia bastar

2021-12-13 20:44 UTC, nicolasviola commented on src/redux/admins/thunks.js
> +        dispatch(addAdminsFulfilled(response.data));
No es necesario agregar el payload porque al redireccionar se va a triggerear una nueva consulta a la lista total de datos

2021-12-17 12:35 UTC, nicolasviola approved these changes

2021-12-17 12:35 UTC, merged