BaSD-MS-56: Reduce Positions
BaSD-2021/Nico-MindSet-app pull request #21
Opened 2021-12-12 07:44 UTC by NicoCagnina

### Refactor and reduce positions entity.
New entity structure:

```
-Positions
    -Form
	-css file
	-index.js
    -Position
	-index.js
 -index.js
 -css file
```

- [x] Refactor
- [x] Redux implemented

2021-12-13 04:16 UTC, ravegliamartin requested changes

2021-12-13 04:16 UTC, ravegliamartin commented on src/Components/Positions/Form/index.js
> +  const [error, setError] = useState('');
You're not setting the error anywhere

2021-12-13 04:16 UTC, ravegliamartin commented on src/Components/Positions/Form/index.js
> +          onClick={onSubmit}
this onClick should be removed, the onSubmit function should remain just in the onSubmit event of the form so the input required attr works as expected.

2021-12-13 04:16 UTC, ravegliamartin commented on src/redux/positions/reducer.js
> +  error: false,
`error` should be a string

2021-12-13 04:16 UTC, ravegliamartin commented on src/redux/positions/reducer.js
> +        list: state.list.filter((positions) => positions._id !== action.payload)
What's the point of this .filter? It will get rid of the updated position.
Perhaps, this piece of logic should reflect the updated position into the global state positions.list

2021-12-13 04:16 UTC, ravegliamartin commented on src/redux/positions/thunks.js
> +        dispatch(addPositionsFulfilled(response.data));
addPositionsFulfilled reducer is not expecting a payload (response.data)

2021-12-13 04:16 UTC, ravegliamartin commented on src/redux/positions/thunks.js
> +        return response.data;
the response.data returned is not in use, it should be removed.

2021-12-13 17:53 UTC, NicoCagnina commented on src/redux/positions/reducer.js
> +        list: state.list.filter((positions) => positions._id !== action.payload)
You are right! Fixed it!

2021-12-13 20:53 UTC, nicolasviola requested changes

2021-12-13 20:53 UTC, nicolasviola commented on src/Components/Positions/Form/index.js
> +    setClientIdValue(data.clientId || 'N/A');
Yo pondria un "" en lugar de un "N/A"

2021-12-13 20:53 UTC, nicolasviola commented on src/Components/Positions/Form/index.js
> +      dispatch(getPositions());
Nico, esto va a funcionar pero es bastante costoso para la aplicacion. imaginate que la lista de positions tenga 10.000 posiciones diferentes y vos por cada una que entras a revisar el formulario, haces un nuevo requerimiento de todas las listas. Claramente la implementacion va a ser super lenta. Te recomiento que para solucionar este tema mires la PR que hizo quito -> https://github.com/BaSD-2021/Esteban-MindSet-app/tree/feature/redux

2021-12-13 20:53 UTC, nicolasviola commented on src/Components/Positions/Form/index.js
> +      positions.map((position) => {
Ojo con esto. El map solo se usa si se pretende devolver un objeto. Para este caso puntual podrias usar un forEach o un find. Usar map para solo iterar un array es una mala practica si no se pretende retornar nada

2021-12-13 20:53 UTC, nicolasviola commented on src/Components/Positions/Position/index.js
> +  const [error, setError] = useState('');
Esto no lo estas usando nunca. Te recomeindo suscribirte al error del store de redux y usar esa variable para triggerear la apertura o no del modal. A su vez crea una action sincronica para limpiar el error en caso de cerrar el modal nuevamente

2021-12-14 00:37 UTC, NicoCagnina commented on src/Components/Positions/Form/index.js
> +      dispatch(getPositions());
Listo! En la forma en la que quito lo hizo cuando salias del update y entrabas a crear uno nuevo, se te precargaban los datos del update anterior. Le tuve que hacer una infima modificacion y va bien.

2021-12-15 02:47 UTC, nicolasviola approved these changes

2021-12-15 02:48 UTC, merged