BaSD-MS-57: Reduce sessions
BaSD-2021/Nico-MindSet-app pull request #24
Opened 2021-12-13 18:10 UTC by NicoCagnina

Refactor following Admins entity PR.

Sessions status: 
- [ ] Select for postulants
- [ ] Select for psychologists
- [x] Inputs
- [x] Redux logic

2021-12-13 21:18 UTC, nicolasviola requested changes

2021-12-13 21:18 UTC, nicolasviola commented on src/Components/Sessions/Form/index.js
> +      session.forEach((session) => {
Mismo comentario que en la otra PR Nico. Fijate como lo manejo quito aca -> https://github.com/BaSD-2021/Esteban-MindSet-app/tree/feature/redux

2021-12-13 21:18 UTC, nicolasviola commented on src/Components/Sessions/Form/index.js
> +    setPostulantsValue(data.postulant || 'N/A');
Por ahi es mejor dejar un "" en lugar de N/A

2021-12-15 04:14 UTC, NicoCagnina commented on src/Components/Sessions/Form/index.js
> +      session.forEach((session) => {
Sisi nico, esto al estar bloqueado lo pause y me puse a corregir la otra PR. Ya esta solucionado esto!

2021-12-15 04:16 UTC, NicoCagnina commented on src/Components/Sessions/Form/index.js
> +    setPostulantsValue(data.postulant || 'N/A');
Lo mismo que arriba. De todas formas los inputs ahora se cargan:

```
    if (sessionId) {
      if (Object.keys(selectedItem).length) {
        setPostulantsValue(selectedItem.postulant.firstName);
        setPsychologistValue(selectedItem.psychology);
        setDateValue(selectedItem.date);
        setTimeValue(selectedItem.time);
        setStatusValue(selectedItem.stat);
      }
    }
```
dado que todos los campos son requeridos, siempre va a volver con un valor.

2021-12-16 16:19 UTC, nicolasviola approved these changes

2021-12-16 16:19 UTC, merged