BaSD-MS-59: Reduce Profiles
BaSD-2021/Nico-MindSet-app pull request #27
Opened 2021-12-14 02:01 UTC by clementinob

### Profiles refactor based on Admins.

- [x]  Implement Redux on entity.
- [x]  Refactor Component to work with Redux.
- [ ]  Refactor Component to unify code with Project.

2021-12-14 17:13 UTC, nicolasviola requested changes

2021-12-14 17:13 UTC, nicolasviola commented on src/Components/Profiles/Form/index.js
> +        setDisableButton(false);
Podrias agregar el disabled anclado a la propiedad isLoading. Si esta cargando que el boton este deshabilitado. Seria bueno reemplazar esta logica por eso que te dije

2021-12-15 21:08 UTC, clementinob commented on src/Components/Profiles/Form/index.js
> +        setDisableButton(false);
Done!

2021-12-15 21:26 UTC, nicolasviola approved these changes

2021-12-15 21:27 UTC, merged