BaSD-MS-62: Reduce Applications
BaSD-2021/Nico-MindSet-app pull request #28
Opened 2021-12-14 02:08 UTC by ripellizzari

**### Refactor made taking into account what's been done on admins entity.**

**Redux Global States implemented.**

--------

Finished: 
-Reduce getApplications
-Reduce deleteApplications
-Refactor Applications.js
-Refactor Application.js

Unfinished:
-Reduce addApplications
-Reduce updateApplications
-Refactor Form

2021-12-16 18:35 UTC, nicolasviola requested changes

2021-12-16 18:35 UTC, nicolasviola commented on src/Components/Applications/Form/index.js
> +  const values = {
Esta constante deberia ser creada dentro de la funcion "onSubmit"

2021-12-16 18:35 UTC, nicolasviola commented on src/redux/applications/reducer.js
> +        if (option.firstName !== undefined) {
Podes hacer directamente if(!option.firstName)

2021-12-16 22:33 UTC, ripellizzari commented on src/Components/Applications/Form/index.js
>          .finally(() =>
Ya fue modificado el codigo.

2021-12-16 22:33 UTC, ripellizzari commented on src/Components/Applications/Form/index.js
> +  const values = {
hecho!

2021-12-16 22:33 UTC, ripellizzari commented on src/redux/applications/reducer.js
> +        if (option.firstName !== undefined) {
Probe de esta manera y me devolvio undefined

2021-12-17 00:02 UTC, nicolasviola approved these changes

2021-12-17 00:02 UTC, merged