BaSD-MS 41: Create Postulants View
BaSD-2021/Nico-MindSet-app pull request #3
Opened 2021-11-29 18:06 UTC by NicoCagnina

# Create Postulants front
Completed the postulant CRUD along with all its functionalities.

## Components used:

- Modal
- List
- Postulant
- Input
- Form

2021-11-30 03:09 UTC, ravegliamartin requested changes

2021-11-30 03:09 UTC, ravegliamartin commented on src/Components/Postulants/List/index.js
> +        if (res.status !== 204) {
The res.status is 200, that's what's defined in the server-side postulant controller. Here you're catching the error and doing nothing with it, so nothing's broken. But ideally, i think this piece of code should be,

```
const handleDelete = (id) => {
    const url = `${process.env.REACT_APP_API}/postulants/${id}`;
    fetch(url, {
      method: 'DELETE'
    })
      .then((res) => {
        if (res.status !== 200) {
            return res.json().then((message) => {
            throw new Error(message);
          });
        }
      setPostulants(dataList.filter((postulants) => postulants._id !== id));
      })
      .catch((error) => {show the error somewhere});
```

2021-11-30 03:09 UTC, ravegliamartin commented on src/Components/Postulants/List/index.js
> +    // };
Comments should be removed

2021-11-30 03:09 UTC, ravegliamartin commented on src/Components/Postulants/Postulant/index.js
> +    console.log(object._id);
`console.log` should be removed

2021-12-01 16:40 UTC, nicolasviola requested changes

2021-12-01 16:40 UTC, nicolasviola commented on src/Components/Postulants/Form/index.js
> +    console.log(data);
Elimina este console.log

2021-12-01 16:40 UTC, nicolasviola commented on src/Components/Postulants/Form/index.js
> +        console.log(error);
Elimina este console.log y crea un state para completar en caso de que haya un error y mostrarlo en el componente

2021-12-01 16:40 UTC, nicolasviola commented on src/Components/Postulants/Form/index.js
> +
Elimina esa linea

2021-12-01 16:40 UTC, nicolasviola commented on src/Components/Postulants/List/index.js
> +        if (res.status !== 204) {
Yeap

2021-12-02 19:32 UTC, merged