BaSD-MS-87: App Authentication
BaSD-2021/Nico-MindSet-app pull request #38
Opened 2022-01-03 23:35 UTC by NicoCagnina

## App Authentication
Created app authentication logic to:

- Postulants
- Psychologists (view not created)
- Admins

### Functions:

- Register postulant
- Login 
    - Postulants 
    - Psychologists 
    - Admins
- Logout

Test users:

> Admin: admin@rr.com
_________________________
> Postulant: postulant@rr.com
_________________________
 Passwords: `12345678`

2022-01-03 23:44 UTC, ravegliamartin approved these changes

2022-01-04 03:16 UTC, Brunomoyano4 commented
In the login screen, if you try to enter with a not register mail, you can view the error in the image.
I think, could be changed for a simple text error, for example, "Email or Password has incorrect" 

![login error](https://user-images.githubusercontent.com/57734335/148003959-d942d4c3-1d8d-4c80-9265-86986363d166.png)

2022-01-04 23:35 UTC, Brunomoyano4 requested changes
Looks good, only change 2 details

2022-01-04 23:35 UTC, Brunomoyano4 commented on src/Components/Auth/Register/index.js
> +    console.log(credentials);
Delete console.log()

2022-01-04 23:35 UTC, Brunomoyano4 commented on src/Routes/index.js
> +          {/* <Redirect to="/postulant?id=61bd751a1d95a30cbccee7c2" /> */}
don´t forget to delete test id postulant

2022-01-04 23:45 UTC, Brunomoyano4 approved these changes
Very good job!

2022-01-05 00:04 UTC, merged