BaSD-MS-101: Create psychologists home
BaSD-2021/Nico-MindSet-app pull request #39
Opened 2022-01-06 21:46 UTC by NicoCagnina

## Create psychologists view

This branch also solves the following tickets: `MS-94` `MS-95` `MS-96`

- [x] Psychologist home view
- [x] Upcoming sessions
- [x] Previous sessions
- [x] Psychologist info card

2022-01-09 21:22 UTC, Brunomoyano4 approved these changes
Looks good for me!

2022-01-11 01:17 UTC, ravegliamartin requested changes

2022-01-11 01:17 UTC, ravegliamartin commented on src/Components/Psychologist/Home/index.js
> +      <section className={styles.container}>
it would be great to have a more responsive design stacking both childs in a column fashion at mobile scenarios.

I believe adding `flex-wrap: wrap` to the `.container` and changing a bit `.userInfoContainer` and `.sessionCard` would do the trick. For instance,

```
.container {
  display: flex;
  justify-content: center;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 3%;
  width: 100%;
  height: 100%;
}
```

```
.userInfoContainer {
  border: 1px solid #d1d1d1;
  border-radius: 5%;
  box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
  width: 35%;
  min-width: 280px
  margin-top: 20px;
  padding: 10px;
}
```

```
.sessionCard {
  display: flex;
  flex-direction: column;
  border: 1px solid #d1d1d1;
  border-radius: 3%;
  box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
  width: 40%;
  min-width: 280px;
  margin-top: 20px;
  padding: 3%;
  max-height: 620px;
}
```

2022-01-11 01:17 UTC, ravegliamartin commented on src/Components/Psychologist/index.js
> +function Home() {
This root component just rendering `PsychologistHome` seems redundant to me. 
It might be removed and then render `PsychologistHome` directly in the psychologistRoutes file.

2022-01-11 21:16 UTC, ravegliamartin approved these changes

2022-01-11 21:58 UTC, merged