BaSD-MS-35: Create Admins View
BaSD-2021/Nico-MindSet-app pull request #4
Opened 2021-11-29 19:20 UTC by clementinob

### Create Admin View
_Components created:_
**Admin
CreateBtn
DeleteBtn
Form
Input
Modal**

_CRUD functionality:_
**List of Admins** on index of entity.
**Create Admin** on index of entity.
**Edit Admin** (clicking in the corresponding row)
**Delete Admin** (clicking in the corresponding button at the end of the row)

2021-11-30 14:19 UTC, ravegliamartin requested changes

2021-11-30 14:19 UTC, ravegliamartin commented on src/Components/Admins/Form/index.js
> +      url = `${process.env.REACT_APP_API}/admins/${adminId}`;
You're already assigning method and url if adminId in line 44-45. This logic is duplicated, I think just one should remain. Perhaps, this one in the `onSubmit` makes more sense, as here in this function is were the fetch is done.

2021-12-01 16:52 UTC, nicolasviola requested changes

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/DeleteBtn/index.js
> +      ></Modal>
Recorda que podes cerrar los elementos que no tienen contenido en la misma etiqueta de cierre. De este modo podes hacer esto:
```
<Modal
        title="Are you sure you want to delete an admin?"
        onConfirm={(e) => deleteAdmin(e)}
        show={showModal}
        closeModal={closeModal}
/>
```

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Form/index.js
> +function Form() {
Deberiamos dejar una linea en blanco entre los imports y la funcion para que sea mas clara la visibilidad del archivo

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Form/index.js
> +    options.method = 'PUT';
Elimina esta logica por lo que puso Rave abajo. No tiene sentido setear en este useEffect la option de una request que vas a hacer en otro lado

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Form/index.js
> +        console.log(error);
Elimina el console.log y arma un setState para manejar este error en caso de que ocurra y mostrarlo en algun lado en el componente

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +  }
La llave deberia estar un tab mas hacia adentro

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +	background: #555;
Ojo este indentado

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +	width: 40%;
Ojo el indentado X2

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +
Esta linea en blanco, hay que borrarla

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +	background: #86d6a5;
AAAAAAAAA el indentadooooooo me duelen los ojosssss lpm revisemos esto

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/Modal/modal.module.css
> +	background: #797878;
Sigo revisando la PR con un ojo menos

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/admins.module.css
> +
Elimina esta linea en blanco

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/admins.module.css
> +
Todas estas lineas Hay que limpiarlas

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/index.js
> +//import EditBtn from './EditBtn';
Elimina el comentario

2021-12-01 16:52 UTC, nicolasviola commented on src/Components/Admins/index.js
> +      });
Hay que agregar el catch con el manejo del error en caso de que hay un error

2021-12-02 18:04 UTC, clementinob commented on src/Components/Admins/Form/index.js
> +      url = `${process.env.REACT_APP_API}/admins/${adminId}`;
Done, Rave! Thanks for pointing me that. :+1:

2021-12-02 18:04 UTC, clementinob commented on src/Components/Admins/DeleteBtn/index.js
> +      ></Modal>
Done!

2021-12-02 18:04 UTC, clementinob commented on src/Components/Admins/Form/index.js
> +function Form() {
Done!

2021-12-02 18:05 UTC, clementinob commented on src/Components/Admins/Form/index.js
> +    options.method = 'PUT';
Done! :smile:

2021-12-02 18:05 UTC, clementinob commented on src/Components/Admins/Form/index.js
> +        console.log(error);
Implemented.

2021-12-02 18:05 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +  }
:heavy_check_mark:

2021-12-02 18:05 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +	background: #555;
:heavy_check_mark:

2021-12-02 18:05 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +	width: 40%;
:heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +
:heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +	background: #86d6a5;
:heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/Modal/modal.module.css
> +	background: #797878;
:heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/admins.module.css
> +
Done :heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/admins.module.css
> +
:heavy_check_mark:

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/index.js
> +//import EditBtn from './EditBtn';
Done!

2021-12-02 18:06 UTC, clementinob commented on src/Components/Admins/index.js
> +      });
Implemented!

2021-12-02 19:37 UTC, nicolasviola approved these changes

2021-12-02 19:37 UTC, merged