BaSD-MS-89: Update Postulant Session View
BaSD-2021/Nico-MindSet-app pull request #40
Opened 2022-01-12 20:34 UTC by clementinob

Add logic to Postulant Session/Interview View to only show one of them based on if the Postulant have at least one Profile Assigned (show Inteviews) or none (show available sessions).

2022-01-13 02:50 UTC, ravegliamartin requested changes

2022-01-13 02:50 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/postulantHome.module.css
The loadingSpinner has a `spinnerContainer` class which is not being set in the `postulantHome.module.css`.

It would be nice to add some style to the spinner so it does not display within the normal flow and therefore no space is reserved for it, neither do the other elements move. For instance,

```
.spinnerContainer {
  position: absolute;
  left: 50%;
  top: 60%;
  transform: translateX(-50%);
}
```

Take into account, for this to work the parent element should have a position of relative:

```
.userInfoContainer {
  ...
  position: relative;
  ...
}
```

2022-01-13 02:50 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/postulantHome.module.css
>  .prof {
While loading, the `div` with class `.prof` is empty, so its height is minimum. When it loads the height is increment to a line-height, and every element below is moved. 
To avoid this element movement we can add some dummy text when the div is empty as follows,

```
.prof:empty::before {
  content: '. . .';
}
```

2022-01-13 22:12 UTC, clementinob commented on src/Components/Postulant/Home/postulantHome/postulantHome.module.css
Done!

2022-01-13 22:12 UTC, clementinob commented on src/Components/Postulant/Home/postulantHome/postulantHome.module.css
>  .prof {
Done!

2022-01-15 00:59 UTC, ravegliamartin requested changes
![image](https://user-images.githubusercontent.com/71772164/149602506-1fae974b-e56c-4115-b131-21c45b2a1248.png)

Perhaps, both big cards (User Info and Available Sessions) might add to a cleaner layout if they are of the same height.

2022-01-15 00:59 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/postulantHome.module.css
>  .cardsInfo {
In this piece of code, I believe lines 194 and 195 are mistaken. 
```
.cardsInfo {
  ...
  align-content: space-between;
  justify-content: center;
  ...
}
```

It should be,
```
.cardsInfo {
  ...
  justify-content: space-between;
  ...
}
```

2022-01-15 00:59 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/index.js
> +                  const formatedSessionsDate = sessionDate.toLocaleDateString();
It would be better if we use a consistent format on dates, being as DD/MM/YYYY (If 1st of February it should be displayed as 01/02/2022).

This can be achieved by adding options to `.toLocaleDateString()` as follows,

```suggestion
                  const formatedSessionsDate = sessionDate.toLocaleDateString(undefined, {
                    year: 'numeric',
                    month: '2-digit',
                    day: '2-digit'
                  });
```

2022-01-15 00:59 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/index.js
>            </div>
The ToggleSwitch component should be disabled while fetching (Line 127 through Line 132)

```
<ToggleSwitch
  label="Available"
  toggled={postulant?.availability}
  onClick={changeAvailability}
  className={styles.toggled}
/>
```

2022-01-15 00:59 UTC, ravegliamartin commented on src/Components/Postulant/Home/postulantHome/index.js
>            </div>
At Line 60 `availabilty: availableValue` should be `availability: availableValue`.
This in the useEffect which begins in Line 55:
``` 
useEffect(() => {
    if (firstUpdate.current) return (firstUpdate.current = false);
    if (postulant) {
      dispatch(
        updatePostulant(postulantId, {
          availabilty: availableValue   <---   Should be availability: availableValue
        })
      );
    }
  }, [availableValue]);
```

2022-01-16 22:15 UTC, NicoCagnina approved these changes

2022-01-16 23:08 UTC, ravegliamartin approved these changes

2022-01-16 23:14 UTC, merged