BaSD-MS-99: Admin Home View
BaSD-2021/Nico-MindSet-app pull request #42
Opened 2022-01-13 02:44 UTC by ripellizzari

### **Create Admin Layout acording to the screenflow**

Admin for testing: 
email: ["admin@rr.com"]
password:"12345678"

- [x] Create Admin Header
- [x] Create Admin Side Bar Menu

The Admin Home Page has a display for Desktop.

2022-01-15 01:09 UTC, NicoCagnina requested changes

2022-01-15 01:09 UTC, NicoCagnina commented on src/Components/Admin/Admins/admins.module.css
> +  display: flex;
the list should not have a display flex

2022-01-15 01:09 UTC, NicoCagnina commented on src/Components/Admin/Admins/admins.module.css
> +  overflow-x:auto;
this line is unnecessary

2022-01-15 01:09 UTC, NicoCagnina commented on src/Components/Admin/Admins/admins.module.css
> +  flex-direction: column;
this line is unnecessary

2022-01-15 14:40 UTC, ripellizzari commented on src/Components/Admin/Admins/admins.module.css
>    margin: 10px 0;
Done!

2022-01-15 14:47 UTC, ripellizzari commented on src/Components/Admin/Admins/admins.module.css
> +  display: flex;
Done!

2022-01-15 14:48 UTC, ripellizzari commented on src/Components/Admin/Admins/admins.module.css
> +  display: flex;
Done!

2022-01-15 14:48 UTC, ripellizzari commented on src/Components/Admin/Admins/admins.module.css
> +  overflow-x:auto;
Done!

2022-01-15 14:48 UTC, ripellizzari commented on src/Components/Admin/Admins/admins.module.css
> +  flex-direction: column;
Done!

2022-01-16 20:46 UTC, NicoCagnina approved these changes

2022-01-16 22:57 UTC, merged