BaSD-MS-38: Create Psychologists View
BaSD-2021/Nico-MindSet-app pull request #5
Opened 2021-11-29 21:16 UTC by clementinob

### Create Psychologists View
_Components created:_

- **CreateBtn**
- **DeleteBtn**
- **Form**
- **Input**
- **Modal**
- **Psychologists**

_CRUD functionality:_
**List of Psychologists** on index of entity.
**Create Psychologist** on index of entity.
**Edit Psychologist** (clicking in the corresponding row)
**Delete Psychologist** (clicking in the corresponding button at the end of the row)

2021-11-30 21:13 UTC, ravegliamartin requested changes
The update function is broken but it's not your fault. 
In the server-side psychologist controller, the update function for this entity is as follow,

```
const editPsychologist = (req, res) => {
  Psychologists.findOneAndUpdate(req.params.id,
    {firstName: req.body.firstName,
    lastName: req.body.lastName,
    userName: req.body.userName,
    email: req.body.email,
    password: req.body.password}, {new : true}
  ) 
  .then((result) => {
    if (!result) {
      return res.status(400).json({
        msg:`Psychologist with id: ${req.params.id} was not found`
      })
    }
    return res.status(201).json(result)
  })
  .catch((error) => {
    return res.status(400).json(error)
  })
}
```

The condition on `findOneAndUpdate` is wrong, it is not referencing any attribute. So, the method creates a new document as it doesn't find a matching existing one. To fix this, the code on the controller should be,

```
const editPsychologist = (req, res) => {
  Psychologists.findOneAndUpdate(
    { _id: req.params.id },
    {
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      userName: req.body.userName,
      email: req.body.email,
      password: req.body.password,
    },
    { new: true }
  )
    .then((result) => {
      if (!result) {
        return res.status(400).json({
          msg: `Psychologist with id: ${req.params.id} was not found`,
        });
      }
      return res.status(201).json(result);
    })
    .catch((error) => {
      return res.status(400).json(error);
    });
};
```

2021-11-30 21:13 UTC, ravegliamartin commented on src/Components/Psychologists/Form/index.js
> +      url = `${process.env.REACT_APP_API}/psychologists/${psychologistId}`;
You're already assigning method and url if adminId in line 44-45. This logic is duplicated, I think just one should remain. Perhaps, this one in the `onSubmit` makes more sense, as here in this function is were the fetch is done.

2021-11-30 21:13 UTC, ravegliamartin commented on src/Components/Psychologists/Form/index.js
> +        return response.json();
Why returning a response.json() if you're doing nothing with that response? Maybe, this piece of code might be refactor as,

```
   fetch(url, options)
      .then((response) => {
        if (response.status !== 200 && response.status !== 201) {
          return response.json().then(({ ErrMessage }) => {
            throw new Error(ErrMessage);
          });
        }
         window.location.href = '/psychologists';
      })
      .catch((error) => {
        console.log(error);
      });
```

2021-12-01 17:01 UTC, nicolasviola requested changes

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/Modal/modal.module.css
> +
Linea en blanco de mas

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/Modal/modal.module.css
> +	border-top-style: none;
Indentado

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/Modal/modal.module.css
> +	background: #86d6a5;
Indentado

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/Modal/modal.module.css
> +	background: #797878;
Indentado

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/index.js
> +      });
Agregar un catch. Lo mismo que te dije mas arriba

2021-12-01 17:01 UTC, nicolasviola commented on src/Components/Psychologists/psychologists.module.css
> +
Linea en blanco de mas

2021-12-02 02:01 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +        return response.json();
Perfect, Rave. Thanks for pointing me that! 👍

2021-12-02 02:02 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +      url = `${process.env.REACT_APP_API}/psychologists/${psychologistId}`;
Done 😄

2021-12-02 02:03 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +function Form() {
Done 👍

2021-12-02 02:18 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +    options.method = 'PUT';
You're right. Done! 😃

2021-12-02 02:20 UTC, clementinob commented on src/Components/Psychologists/DeleteBtn/index.js
> +      .finally(window.location.reload());
Yeap, my bad. Consider it done 👍

2021-12-02 02:45 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +        });
Implemented!

2021-12-02 02:45 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +	background: #555;
✔️

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +	width: 40%;
✔️

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +
Done

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +	border-top-style: none;
✔️

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +	background: #86d6a5;
✔️

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/Modal/modal.module.css
> +	background: #797878;
✔️

2021-12-02 02:46 UTC, clementinob commented on src/Components/Psychologists/psychologists.module.css
> +
Done!

2021-12-02 13:05 UTC, clementinob commented on src/Components/Psychologists/Form/index.js
> +        console.log(error);
Implemented!

2021-12-02 16:46 UTC, clementinob commented on src/Components/Psychologists/index.js
> +      });
Implemented!

2021-12-02 19:36 UTC, nicolasviola approved these changes

2021-12-02 19:36 UTC, merged