BaSD-MS-37: Create Interviews View
BaSD-2021/Nico-MindSet-app pull request #6
Opened 2021-11-30 02:31 UTC by ripellizzari

Components: 
-AddBtn
-Form
-Input
-Interview
-Modal
-Select

CRUD: 
List of Interviews.
Create a new Interview.
Update an interview.
Delete an interview.

2021-12-01 17:11 UTC, nicolasviola requested changes

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/AddBtn/addBtn.module.css
> +	box-sizing: border-box;
Indentadoooo

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/AddBtn/addBtn.module.css
> +	background: #2EBC99;
Y aca, son 2 espacios o 1 tab de dos espacios y aca hay 4 espacios

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/AddBtn/addBtn.module.css
> +	background: #555;
Lo mismo

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Form/form.module.css
> +	max-width: 400px;
Aca lo mismo, fijate que la ultima prop esta bien y las demas son nada que ver

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Form/index.js
> +        });
Tenes que agregar un catch para los casos en que exista un error desde el server. Dentro del catch podes crear un nuevo state para mostrar un mensaje genérico de error cuando exista en la UI

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Form/index.js
> +        error.innerText = error;
Mmmm ese innerText no tiene mucho sentido usando react. Deberias crear un state, y en la fucnion que setea ese state de error agregar un error generico en caso de que exista un error para mostrar

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Input/input.module.css
> +	box-sizing: border-box;
Indentado

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Interview/index.js
> +    console.log('se borro');
Esta función solo muestra un console.log. Si no vas a hacer otra cosa borra la funcion y sino agregale el codigo correspondiente

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Interview/interview.module.css
> +	width: 100%;
Indentadoooooo

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/Interview/interview.module.css
> +	background: #2EBC99;
Aca tambien indentado

2021-12-01 17:11 UTC, nicolasviola commented on src/Components/Interviews/interviews.module.css
> +	padding: 12px 15px;
Indentado

2021-12-01 17:22 UTC, nicolasviola requested changes

2021-12-01 17:22 UTC, nicolasviola commented on src/Components/Interviews/Form/form.module.css
> +    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
Indentado

2021-12-01 17:22 UTC, nicolasviola commented on src/Components/Interviews/Input/input.module.css
> +    outline: none;
Indentado

2021-12-01 17:22 UTC, nicolasviola commented on src/Components/Interviews/interviews.module.css
> +}
Agregar una linea en blanco que divida las clases

2021-12-02 04:36 UTC, ripellizzari commented on src/Components/Interviews/Modal/modal.module.css
> +      width: 40%;
AJAJAJA PERDON!!! Estuve teniendo un problema Nico, con los indentados igual... cuando guardo se me corre una linea o mas o menos en algunos module.css

2021-12-02 19:33 UTC, nicolasviola approved these changes

2021-12-02 19:33 UTC, merged